DOSE-759 Zoa panicked at assertion failed: (left > right) (#543)
Pool::end_txg() assumes that the syncing_txg will be None if we are
redoing a "end txg" request that we actually completed before the agent
crashed.  We need to do this explicitly, now that the kernel passes the
resuming_txg as part of of the "open pool" request.